In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('spam.csv')
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
df.shape

(5572, 3)

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [8]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [9]:
type(X_train)

pandas.core.series.Series

In [14]:
type(X_train.values)

numpy.ndarray

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7777 sparse matrix of type '<class 'numpy.int64'>'
	with 59996 stored elements in Compressed Sparse Row format>

In [15]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
X_train_cv.shape

(4457, 7777)

In [20]:
v.get_feature_names_out()[6771:6781]

array(['teachers', 'teaches', 'teaching', 'team', 'teams', 'tear',
       'tears', 'tease', 'teasing', 'tech'], dtype=object)

In [21]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixed_vocabulary_',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'get_stop_words',
 'input',
 'inverse_transform',
 'lowercase',
 'max_df',
 'max_features',
 'min_df',
 'ngram_range',
 'preprocessor',
 'set_params',
 'stop_words',
 'strip_accents',
 'token_pattern',
 'tokenizer',
 'transform',
 'vocabulary',
 'vocabulary_']

In [22]:
v.vocabulary_

{'haha': 3317,
 'can': 1636,
 'but': 1581,
 'having': 3386,
 'dinner': 2347,
 'with': 7577,
 'my': 4698,
 'cousin': 2055,
 'shopping': 6150,
 'lor': 4244,
 'them': 6864,
 'raining': 5587,
 'mah': 4352,
 'hard': 3357,
 'leave': 4100,
 'orchard': 5015,
 'ex': 2704,
 'wife': 7540,
 'was': 7418,
 'not': 4860,
 'able': 767,
 'to': 6968,
 'have': 3380,
 'kids': 3970,
 'do': 2392,
 'you': 7736,
 'want': 7406,
 'one': 4974,
 'day': 2190,
 'evry': 2701,
 'emotion': 2595,
 'dsn': 2490,
 'hav': 3377,
 'words': 7616,
 'wish': 7570,
 'prayrs': 5408,
 'if': 3630,
 'smile': 6293,
 'world': 7624,
 'is': 3781,
 'wit': 7576,
 'othrwise': 5039,
 'even': 2676,
 'drop': 2475,
 'of': 4926,
 'tear': 6776,
 'lik': 4152,
 'stay': 6501,
 'so': 6322,
 'happy': 3356,
 'good': 3199,
 'morning': 4626,
 'keep': 3944,
 'smiling': 6297,
 'well': 7486,
 'for': 2957,
 'class': 1838,
 'babe': 1182,
 'never': 4787,
 'came': 1631,
 'back': 1190,
 'me': 4445,
 'hope': 3517,
 'nice': 4802,
 'sleep': 6260,
 'love': 4265,
 'mean': 4448,
 'the': 6856,
 'website': 7459,
 'yes': 7720,
 'hello': 3422,
 'beautiful': 1274,
 'ok': 4949,
 've': 7293,
 'kinda': 3978,
 'ad': 810,
 'row': 5872,
 'wiv': 7583,
 'and': 958,
 'he': 3391,
 'walked': 7393,
 'out': 5046,
 'pub': 5524,
 'wanted': 7408,
 'night': 4810,
 'miss': 4546,
 'yup': 7760,
 'wun': 7669,
 'believe': 1307,
 'wat': 7424,
 'really': 5648,
 'neva': 4785,
 'msg': 4653,
 'sent': 6058,
 'shuhui': 6183,
 'place': 5272,
 'all': 910,
 'ur': 7232,
 'points': 5326,
 'on': 4968,
 'cultures': 2123,
 'module': 4595,
 'already': 921,
 'buy': 1586,
 'space': 6391,
 'invaders': 3752,
 'chance': 1730,
 'win': 7550,
 'orig': 5025,
 'arcade': 1043,
 'game': 3080,
 'console': 1991,
 'press': 5433,
 'games': 3081,
 'std': 6505,
 'wap': 7411,
 'charge': 1741,
 'see': 6021,
 'o2': 4908,
 'co': 1882,
 'uk': 7153,
 'terms': 6811,
 'settings': 6075,
 'no': 4826,
 'purchase': 5534,
 'come': 1919,
 'tampa': 6743,
 'ffffuuuuuuu': 2839,
 'probably': 5464,
 'almost': 917,
 'gas': 3093,
 'get': 3131,
 'some': 6335,
 'cash': 1682,
 'tomorrow': 6991,
 'we': 7446,
 'made': 4344,
 'it': 3792,
 'eta': 2665,
 'at': 1109,
 'taunton': 6757,
 '12': 280,
 '30': 423,
 'as': 1081,
 'planned': 5280,
 'that': 6852,
 'still': 6521,
 'okday': 4951,
 'xx': 7684,
 'under': 7175,
 'sea': 6002,
 'there': 6874,
 'lays': 4081,
 'rock': 5846,
 'in': 3671,
 'an': 954,
 'envelope': 2637,
 'paper': 5107,
 'are': 1045,
 '100': 257,
 'music': 4688,
 'gift': 3144,
 'vouchers': 7360,
 'every': 2683,
 'week': 7469,
 'starting': 6491,
 'now': 4874,
 'txt': 7124,
 'word': 7615,
 'draw': 2457,
 '87066': 696,
 'tscs': 7095,
 'www': 7670,
 'idew': 3625,
 'com': 1914,
 'skillgame': 6245,
 '1winaweek': 344,
 'age16': 862,
 '150ppermesssubscription': 309,
 'meeting': 4464,
 'da': 2153,
 'ge': 3111,
 'nite': 4821,
 'tmr': 6963,
 'what': 7505,
 'need': 4760,
 'person': 5206,
 'give': 3157,
 'na': 4707,
 'loving': 4275,
 'dont': 2427,
 'gimme': 3149,
 'lip': 4180,
 'caveboy': 1701,
 'dating': 2186,
 'service': 6070,
 'cal': 1606,
 '09064012103': 209,
 'box334sk38ch': 1461,
 'wanna': 7405,
 'watch': 7425,
 'movie': 4643,
 'also': 924,
 'remember': 5727,
 'beads': 1269,
 'don': 2424,
 'off': 4928,
 'ever': 2682,
 'painful': 5089,
 'thought': 6903,
 'being': 1306,
 'most': 4631,
 'toughest': 7033,
 'thing': 6882,
 'earth': 2522,
 'acting': 803,
 'unspoken': 7210,
 'pain': 5088,
 'inside': 3723,
 'pls': 5299,
 'help': 3425,
 'tell': 6792,
 'ashley': 1085,
 'cant': 1647,
 'find': 2871,
 'her': 3437,
 'number': 4888,
 'oh': 4945,
 'surely': 6665,
 'forgot': 2969,
 'will': 7548,
 'always': 930,
 'be': 1267,
 'touch': 7030,
 'say': 5961,
 'leh': 4111,
 'course': 2052,
 'nothing': 4864,
 'happen': 3347,
 'lar': 4055,
 'romantic': 5856,
 'jus': 3907,
 'bit': 1366,
 'only': 4980,
 'thk': 6893,
 'scenery': 5973,
 'hi': 3452,
 'baby': 1184,
 'im': 3647,
 'cruisin': 2102,
 'girl': 3152,
 'friend': 3019,
 'up': 7217,
 'call': 1612,
 'hour': 3544,
 'home': 3500,
 'thats': 6855,
 'alright': 922,
 'or': 5008,
 'fone': 2944,
 'this': 6892,
 'jenny': 3844,
 'xxx': 7686,
 'sam': 5928,
 'eachother': 2515,
 'meet': 4462,
 'go': 3176,
 'house': 3547,
 'wonders': 7608,
 '7th': 643,
 '6th': 615,
 'style': 6584,
 '5th': 570,
 '4th': 529,
 'personality': 5209,
 '3rd': 470,
 'nature': 4739,
 '2nd': 403,
 'sms': 6304,
 '1st': 339,
 'lovely': 4268,
 'friendship': 3021,
 'dear': 2203,
 'idc': 3620,
 'over': 5060,
 'here': 3438,
 'weaseling': 7453,
 'your': 7740,
 'way': 7441,
 'shit': 6135,
 'twice': 7116,
 'ard': 1044,
 'like': 4153,
 'dat': 2182,
 'when': 7511,
 'finish': 2877,
 'then': 6868,
 'pick': 5245,
 'deepest': 2227,
 'darkest': 2176,
 'fantasies': 2790,
 '09094646631': 245,
 'just': 3908,
 '60p': 580,
 'min': 4521,
 'stop': 6533,
 'texts': 6837,
 '08712460324': 112,
 'nat': 4731,
 'rate': 5612,
 'clarify': 1834,
 'open': 4991,
 'return': 5800,
 'ticket': 6927,
 'preponed': 5424,
 'kerala': 3952,
 're': 5628,
 'gonna': 3197,
 'more': 4622,
 'specific': 6409,
 'than': 6840,
 'new': 4790,
 'voicemail': 7351,
 'please': 5292,
 '08719181513': 153,
 'isn': 3788,
 'decision': 2217,
 'feeling': 2821,
 'could': 2041,
 'decide': 2213,
 'who': 7525,
 'life': 4142,
 'would': 7639,
 'much': 4670,
 'simpler': 6210,
 'less': 4122,
 'magical': 4351,
 'll': 4202,
 'join': 3869,
 'lt': 4288,
 'gt': 3281,
 'bus': 1574,
 'honeybee': 3507,
 'said': 5917,
 'sweetest': 6691,
 'god': 3182,
 'laughed': 4071,
 'amp': 948,
 'wait': 7384,
 'havnt': 3388,
 'met': 4500,
 'reading': 5638,
 'moral': 4621,
 'crack': 2066,
 'jokes': 3874,
 'gm': 3170,
 'gn': 3172,
 'ask': 1088,
 'they': 6879,
 'next': 4798,
 'sat': 5947,
 'make': 4364,
 'dunno': 2503,
 'lei': 4112,
 'how': 3551,
 'abt': 772,
 'leona': 4119,
 'oops': 4990,
 'tot': 7026,
 'ben': 1316,
 'going': 3188,
 'him': 3460,
 'once': 4972,
 'free': 2998,
 'sir': 6226,
 'sorry': 6371,
 'later': 4067,
 'change': 1732,
 'sentence': 6059,
 'into': 3748,
 'because': 1278,
 'concentrate': 1962,
 'educational': 2546,
 'career': 1664,
 'leaving': 4102,
 'sheffield': 6117,
 'tom': 6987,
 'air': 882,
 'opinions': 4999,
 'categories': 1695,
 'used': 7248,
 'measure': 4454,
 'ethnicity': 2667,
 'census': 1714,
 'busy': 1580,
 'transcribing': 7052,
 'why': 7533,
 'de': 2197,
 'looking': 4239,
 'mum': 4675,
 'present': 5430,
 'ar': 1042,
 'got': 3216,
 'tallent': 6741,
 'wasting': 7423,
 'watching': 7429,
 'footie': 2954,
 'worried': 7627,
 'blow': 1401,
 'phil': 5227,
 'neville': 4788,
 'read': 5635,
 'answered': 981,
 'know': 3996,
 'watchin': 7428,
 'lido': 4139,
 'hey': 3448,
 'sweet': 6690,
 'wondering': 7607,
 'had': 3314,
 'moment': 4602,
 'might': 4511,
 'send': 6049,
 'file': 2855,
 'someone': 6339,
 'won': 7603,
 'yahoo': 7698,
 'their': 6862,
 'connection': 1984,
 'sucks': 6609,
 'set': 6073,
 'page': 5084,
 'download': 2443,
 'format': 2975,
 'disc': 2363,
 'other': 5035,
 'big': 1346,
 'files': 2856,
 'stuff': 6577,
 'directly': 2353,
 'from': 3033,
 'internet': 3744,
 'any': 991,
 'great': 3253,
 'prey': 5442,
 'teasing': 6779,
 'kiss': 3985,
 '07734396839': 28,
 'ibh': 3605,
 'customer': 2140,
 'loyalty': 4282,
 'offer': 4933,
 'nokia6600': 4836,
 'mobile': 4581,
 '10': 256,
 'txtauction': 7128,
 'start': 6489,
 '81151': 660,
 'yours': 7744,
 '4t': 528,
 'idk': 3627,
 'saying': 5963,
 'since': 6214,
 'moved': 4641,
 'butting': 1584,
 'heads': 3396,
 'freedom': 3000,
 'vs': 7362,
 'responsibility': 5786,
 'tired': 6944,
 'deal': 2199,
 'barely': 1225,
 'keeping': 3945,
 'myself': 4702,
 'together': 6978,
 'gets': 3133,
 'added': 814,
 'getting': 3137,
 'goods': 3209,
 'time': 6938,
 'flight': 2911,
 'shall': 6101,
 'hear': 3401,
 'holiday': 3495,
 'monday': 4606,
 'dentists': 2263,
 'calls': 1626,
 'messages': 4495,
 'missed': 4548,
 'telling': 6793,
 'treat': 7069,
 'thank': 6843,
 'winner': 7560,
 'notified': 4867,
 'by': 1597,
 'luck': 4293,
 'future': 3064,
 'marketing': 4398,
 'reply': 5755,
 '84122': 680,
 'services': 6071,
 '08450542832': 65,
 'ned': 4759,
 'toa': 6969,
 'payoh': 5167,
 'while': 7520,
 'smth': 6309,
 'wan': 7402,
 'shock': 6144,
 'cos': 2031,
 'liao': 4133,
 'reaction': 5634,
 'sitting': 6236,
 'shop': 6148,
 'parking': 5125,
 'lot': 4251,
 'right': 5821,
 'bawling': 1249,
 'eyes': 2755,
 'feel': 2819,
 'failure': 2772,
 'everything': 2692,
 'nobody': 4829,
 'wants': 7410,
 'failing': 2770,
 'does': 2403,
 'dance': 2165,
 'river': 5839,
 'reached': 5631,
 'unable': 7164,
 'connect': 1982,
 'uncles': 7169,
 'atlanta': 1113,
 'guys': 3304,
 'semester': 6045,
 'school': 5976,
 'lab': 4025,
 'doing': 2416,
 'done': 2425,
 'check': 1761,
 'mail': 4356,
 'mailed': 4358,
 'varma': 7284,
 'kept': 3951,
 'copy': 2021,
 'regarding': 5702,
 'membership': 4477,
 'take': 6726,
 'care': 1661,
 'insha': 3721,
 'allah': 911,
 'tkts': 6957,
 'euro2004': 2671,
 'cup': 2127,
 'final': 2866,
 '800': 645,
 'collect': 1904,
 '09058099801': 185,
 'b4190604': 1176,
 'pobox': 5309,
 '7876150ppm': 637,
 'necessarily': 4754,
 'respectful': 5780,
 'lets': 4127,
 'saturday': 5954,
 'per': 5187,
 'convenience': 2007,
 'am': 932,
 'station': 6499,
 'dude': 2495,
 'buff': 1552,
 'wind': 7552,
 'mesages': 4491,
 'today': 6974,
 'hurts': 3591,
 'boo': 1424,
 'enjoyin': 2619,
 'yourjob': 7743,
 'seemed': 6027,
 'gettin': 3136,
 'hunny': 3584,
 'ure': 7234,
 'llspeak': 4203,
 '2u': 414,
 'soonlots': 6363,
 'loveme': 4269,
 'xxxx': 7688,
 'tried': 7074,
 'contact': 1994,
 '750': 627,
 'pound': 5379,
 'prize': 5458,
 'claim': 1830,
 'easy': 2529,
 '08712101358': 96,
 '10p': 267,
 'bt': 1541,
 'national': 4736,
 'st': 6469,
 'andre': 960,
 'virgil': 7334,
 'cream': 2079,
 'ringtone': 5829,
 'waiting': 7387,
 'collected': 1905,
 'simply': 6211,
 'text': 6826,
 'password': 5143,
 'mix': 4563,
 '85069': 686,
 'verify': 7303,
 'usher': 7254,
 'britney': 1516,
 'fml': 2933,
 'po': 5307,
 'box': 1454,
 '5249': 556,
 'mk17': 4565,
 '92h': 734,
 '450ppw': 502,
 '16': 318,
 'captain': 1654,
 'vijaykanth': 7323,
 'comedy': 1920,
 'tv': 7112,
 'drunken': 2486,
 'gr8': 3228,
 'live': 4195,
 'sex': 6081,
 'video': 7317,
 'chat': 1753,
 'mob': 4579,
 'sexiest': 6082,
 'dirtiest': 2357,
 'girls': 3154,
 'phone': 5232,
 'details': 2290,
 'horny': 3528,
 '89070': 714,
 'cancel': 1640,
 'private': 5456,
 '2003': 351,
 'account': 791,
 'statement': 6497,
 'shows': 6175,
 'un': 7163,
 'redeemed': 5688,
 '08719899230': 157,
 'identifier': 3624,
 'code': 1892,
 '41685': 485,
 'expires': 2737,
 '07': 19,
 '11': 269,
 '04': 13,
 'buzzzz': 1593,
 'grins': 3263,
 'did': 2316,
 'buzz': 1592,
 'ass': 1096,
 'chest': 1779,
 'cock': 1889,
 'where': 7514,
 'vibrator': 7313,
 'shake': 6098,
 'aathi': 758,
 'cost': 2032,
 'hire': 3465,
 'hitman': 3470,
 'calling': 1625,
 'times': 6939,
 'lil': 4158,
 'noon': 4845,
 'darren': 2179,
 'den': 2256,
 'dun': 2501,
 'xy': 7694,
 'awkward': 1166,
 'lunch': 4300,
 'taking': 6731,
 'part': 5126,
 'our': 5043,
 'survey': 6674,
 'yesterday': 7722,
 '500': 541,
 'use': 7247,
 'however': 3554,
 'txts': 7132,
 '80160': 652,
 'txt43': 7126,
 '50p': 546,
 'its': 3799,
 'yourself': 7745,
 'carlos': 1671,
 'says': 5964,
 'mu': 4668,
 'minutes': 4539,
 'yo': 7731,
 'stock': 6524,
 'trying': 7092,
 'dubsack': 2493,
 'ready': 5639,
 'elaine': 2572,
 'confirmed': 1976,
 'man': 4374,
 'accidentally': 786,
 'left': 4106,
 'silent': 6203,
 'last': 4061,
 'didn': 2318,
 'til': 6935,
 'sure': 6664,
 'understand': 7177,
 'wine': 7556,
 'idea': 3621,
 'slurp': 6283,
 'gud': 3286,
 'mrng': 4650,
 'chief': 1788,
 'bell': 1309,
 'talk': 6734,
 'about': 769,
 'royal': 5874,
 'visit': 7340,
 'june': 3903,
 'checking': 1764,
 'message': 4493,
 '08712400200': 102,
 'mallika': 4373,
 'sherawat': 6120,
 'url': 7240,
 'erutupalam': 2655,
 'thandiyachu': 6841,
 'weekend': 7471,
 'haven': 3382,
 'slept': 6267,
 'past': 5145,
 'few': 2835,
 'nights': 4812,
 'princess': 5449,
 'entry': 2633,
 'weekly': 7473,
 'comp': 1933,
 'ipod': 3771,
 'pod': 5323,
 '80182': 653,
 'apply': 1024,
 '08452810073': 67,
 '18': 322,
 'texted': 6832,
 'pshew': 5515,
 'missing': 4550,
 'regret': 5707,
 'inform': 3705,
 'nhs': 4799,
 'has': 3367,
 'mistake': 4556,
 'were': 7494,
 'actually': 809,
 'born': 1439,
 'report': 5758,
 'yor': 7734,
 'local': 4210,
 'hospital': 3533,
 '2b': 380,
 'terminated': 6810,
 'inconvenience': 3683,
 'food': 2947,
 'naked': 4714,
 'hot': 3538,
 '69698': 599,
 'charged': 1742,
 '150pm': 308,
 'unsubscribe': 7212,
 'significance': 6197,
 'sending': 6051,
 'blackberry': 1373,
 'torch': 7019,
 'nigeria': 4808,
 'buyer': 1587,
 '4a': 512,
 'month': 4615,
 'dad': 2156,
 'bb': 1251,
 'anyone': 995,
 'lol': 4224,
 'these': 6875,
 'ideas': 3623,
 'pizza': 5270,
 'jesus': 3852,
 'christ': 1817,
 'bitch': 1367,
 'drugs': 2482,
 'answer': 980,
 'fucking': 3044,
 'aaooooright': 757,
 'work': 7617,
 '0776xxxxxxx': 31,
 'been': 1290,
 'invited': 3758,
 'xchat': 7677,
 'attempt': 1120,
 '86688': 693,
 '150p': 306,
 'msgrcvdhg': 4657,
 'suite342': 6625,
 '2lands': 396,
 'w1j6hl': 7369,
 'ldn': 4086,
 '18yrs': 325,
 'crucify': 2099,
 'should': 6160,
 'told': 6983,
 'earlier': 2517,
 'anything': 999,
 'drastic': 2456,
 'dare': 2173,
 'sell': 6041,
 'pc': 5169,
 'plans': 5282,
 'yet': 7723,
 'somerset': 6341,
 'far': 2793,
 'tomo': 6990,
 'soon': 6361,
 'car': 1656,
 'tonight': 7000,
 'rain': 5586,
 'spoil': 6441,
 'bed': 1284,
 'sindu': 6216,
 'job': 3862,
 'birla': 1360,
 'soft': 6327,
 'forwarded': 2983,
 '21870000': 359,
 'mailbox': 4357,
 'messaging': 4496,
 'alert': 898,
 '21': 358,
 'matches': 4416,
 '09056242159': 171,
 'retrieve': 5799,
 'wil': 7545,
 'thanks': 6844,
 'picking': 5247,
 'trash': 7059,
 'thinkin': 6886,
 'malaria': 4369,
 'relax': 5715,
 'children': 1794,
 'handle': 3335,
 'she': 6114,
 'worse': 7631,
 'gastroenteritis': 3094,
 'takes': 6729,
 'enough': 2623,
 'replace': 5750,
 'loss': 4249,
 'temp': 6800,
 'reduce': 5689,
 'meds': 4460,
 'vomit': 7354,
 'self': 6037,
 'limiting': 4163,
 'illness': 3644,
 'which': 7519,
 'means': 4451,
 'days': 2191,
 'completely': 1948,
 'poly': 5333,
 'tones': 6994,
 'mobs': 4587,
 'direct': 2352,
 'rply': 5876,
 'title': 6950,
 '8007': 647,
 'eg': 2558,
 'breathe1': 1497,
 'titles': 6951,
 'crazyin': 2077,
 'sleepingwith': 6263,
 'finest': 2875,
 'ymca': 7730,
 'getzed': 3138,
 'pobox365o4w45wq': 5316,
 '300p': 428,
 'wan2': 7403,
 'greet': 3259,
 'westlife': 7500,
 'm8': 4324,
 'currently': 2133,
 'tour': 7034,
 'unbreakable': 7166,
 'untamed': 7214,
 'unkempt': 7198,
 '83049': 667,
 'specially': 6408,
 'selected': 6035,
 'receive': 5665,
 '2000': 350,
 'award': 1162,
 '08712402050': 104,
 'before': 1296,
 'lines': 4171,
 'close': 1859,
 '10ppm': 268,
 'cs': 2106,
 'ag': 857,
 'promo': 5492,
 'pattern': 5153,
 'emerging': 2592,
 'friends': 3020,
 'drive': 2469,
 'smoke': 6299,
 'weed': 7468,
 'fiend': 2845,
 'too': 7005,
 'impede': 3659,
 'things': 6883,
 'hesitant': 3444,
 'peach': 5174,
 'cake': 1604,
 'tasts': 6751,
 'lush': 4302,
 'die': 2321,
 'late': 4064,
 'early': 2519,
 'juz': 3913,
 'aiya': 885,
 'camera': 1632,
 'awarded': 1163,
 'sipix': 6224,
 'digital': 2335,
 '09061221066': 191,
 'fromm': 3034,
 'landline': 4043,
 'delivery': 2251,
 'within': 7579,
 '28': 374,
 'doin': 2414,
 'okay': 4950,
 'luv': 4303,
 'ya': 7696,
 'awesome': 1165,
 'restocked': 5790,
 'aight': 879,
 'lemme': 4114,
 'special': 6404,
 '000': 1,
 'call09050000327': 1613,
 'after': 853,
 'wkend': 7586,
 'valentine': 7272,
 'dis': 2359,
 'answers': 984,
 'same': 5931,
 'loves': 4273,
 'ques': 5560,
 'colour': 1911,
 'suits': 6626,
 'best': 1323,
 'bring': 1509,
 'success': 6603,
 '2004': 352,
 '07742676969': 29,
 '786': 636,
 'unredeemed': 7207,
 'bonus': 1423,
 '08719180248': 151,
 '45239': 503,
 'asked': 1090,
 'anand': 957,
 'difference': 2328,
 'versus': 7306,
 'hrs': 3562,
 'jamster': 3821,
 'wallpaper': 7397,
 'heart': 3405,
 '88888': 712,
 '08701213186': 73,
 'wonder': 7605,
 'think': 6884,
 'crazy': 2076,
 'away': 1164,
 'another': 977,
 '1hr': 333,
 'delay': 2243,
 'voucher': 7359,
 'holder': 3492,
 'airport': 883,
 'lounge': 4261,
 'passes': 5139,
 'using': 7255,
 '08704439680': 84,
 'booking': 1428,
 'quote': 5574,
 'people': 5186,
 'dogging': 2410,
 'area': 1046,
 ...}

In [23]:
X_train_np = X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
np.where(X_train_np[0]>0)

(array([1581, 1636, 2055, 2347, 3317, 3386, 4698, 7577]),)

In [25]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [26]:
X_test_cv = v.transform(X_test)

In [27]:
model.score(X_train_cv, y_train)

0.9921471842046219

In [35]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = model.predict(X_test_cv)

In [34]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       973
           1       0.98      0.92      0.95       142

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

In [31]:
confusion_matrix(y_test, y_pred)

array([[971,   2],
       [ 12, 130]])

In [32]:
accuracy_score(y_test, y_pred)

0.9874439461883409

In [36]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [37]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb_model', MultinomialNB())
])

In [38]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('nb_model', MultinomialNB())])

In [39]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       973
           1       0.98      0.92      0.95       142

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115