In [1]:
import pandas as pd

df = pd.read_csv('Fake_Real_Data.csv')
df.head()

                                                Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1  U.S. conservative leader optimistic of common ...  Real
2  Trump proposes U.S. tax overhaul, stirs concer...  Real
3   Court Forces Ohio To Allow Millions Of Illega...  Fake
4  Democrats say Trump agrees to work on immigrat...  Real

In [2]:
df.shape

(9900, 2)

In [3]:
df.label.value_counts()

label
Fake    5000
Real    4900
Name: count, dtype: int64

In [4]:
df['label_num']= df['label'].map({'FAKE':0, 'REAL':1})
df.head()

                                                Text label  label_num
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake        NaN
1  U.S. conservative leader optimistic of common ...  Real        NaN
2  Trump proposes U.S. tax overhaul, stirs concer...  Real        NaN
3   Court Forces Ohio To Allow Millions Of Illega...  Fake        NaN
4  Democrats say Trump agrees to work on immigrat...  Real        NaN

In [5]:
import spacy
nlp = spacy.load('en_core_web_lg')

In [6]:
doc = nlp("Top trump Surrogate BRUTAllY Stabs His Victim To DeATh Over Dispute")
doc.vector.shape

(300,)

In [7]:
df['vector'] = df['Text'].apply(lambda text: nlp(text).vector)

In [8]:
df.head()

,Text,label,label_num,vector
0,Top Trump Surrogate BRUTALLY Stabs Him In The...,Fake,NaN,"[-0.103623025, 0.17802684, -0.11873861, -0.034..."
1,U.S. conservative leader optimistic of common ...,Real,NaN,"[-0.0063406364, 0.16712041, -0.06661373, 0.017..."
2,"Trump proposes U.S. tax overhaul, stirs concer...",Real,NaN,"[-0.122753024, 0.17192385, -0.024732638, -0.06..."
3,Court Forces Ohio To Allow Millions Of Illega...,Fake,NaN,"[-0.027337318, 0.12501417, -0.0073965387, -0.0..."
4,Democrats say Trump agrees to work on immigrat...,Real,NaN,"[-0.032708026, 0.093958504, -0.03287002, -0.00..."

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.vector.values,
    df.label_num,
    test_size=0.2,
    random_state=2022
)

In [10]:
import numpy as np

X_train_2d = np.stack(X_train)
X_test_2d = np.stack(X_test)

In [12]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler()
scaled_train_embed = scaler.fit_transform(X_train_2d)
scaled_test_embed = scaler.transform(X_test_2d)


clf = MultinomialNB()
clf.fit(scaled_train_embed, y_train)

ValueError: Input y contains NaN.

In [ ]:
y_pred = clf.predict(scaled_test_embed)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

In [ ]:
from  sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean')

clf.fit(X_train_2d, y_train)

y_pred = clf.predict(X_test_2d)

print(classification_report(y_test, y_pred))

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

from matplotlib import pyplot as plt
import seaborn as sn
plt.figure(figsize = (10,7))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Prediction')
plt.ylabel('Truth')